export const URLS={
  //  fir chick bdba12ca-a874-4178-9b5f-d009f0a1ab9a
  // pizza  21 360de0c6-8107-49b9-b3c1-7463aa2e17c0
    GOOGLE_MAP_KEY:"AIzaSyB4IiJ7-RLQuovoGa_sj5HaBNBZ5vPYzT0",
    ENTITY_UID:"bdba12ca-a874-4178-9b5f-d009f0a1ab9a",
    BASE_URL:"https://loyalty.droidor.com/api/",
    STRIPE_LIVE_URL:"https://loyalty.droidor.com/stripe/",
    STRIPE_PAYMENT_METHOD_ADDED:"paymentMethodAdded",
    GET_PAYMENT_METHODS:"v1/getPaymentMethods",
    AUTH:"auth",
    AUTHENTICATE_OTP:"authenticate-otp",
    RESEND_OTP:"resend-otp",
    UPDATE_PROFILE:"user/update-profile",
    UPDATE_NUMBER:"user/update-phone-number",
    VALIDATE_EMAIL:"user/validate-email",
    VALIDATE_PHONE:"user/validate-phone-number",
    UPDATE_PROFILE_PICTURE:"user/update-profile-picture",
    GET_HOME_PAGE:"v1/getHomePageContent",
    BRANCHES:"v1/branches",
    BRANCH_FAVORITE :"/v1/favorite",
    GET_MANUE_PAGE:"v1/getManuPageContent",
    PRODUCT_CATEGORIES:"v1/getProductsCategories",
    MENU:"v1/getMenu",
    PRODUCT_DETAIL:"v1/productDetail",
    ADDRESS_LIST:"v1/getUserAddressList",
    ADD_USER_ADDRESS:"v1/addUserAddress",
    POPULAR_PRODUCTS:"v1/getPopularProducts",
    DELETE_ADDRESS:"v1/deleteUserAddress",
   ADD_STRIPE_PAYMENT: "addPaymentMethodStrip",
   DELETE_STRIPE_PAYMENT:"v1/deletePaymentMethod",
   PLACE_ORDER:"v1/placeOrder",
   ORDER_HISTORY:"v1/orderHistory",
  ACTIVE_ORDERS :"v1/activeOrders",
   GET_NOTIFICATIONS:"v1/getNotifications",
   DELETE_USER:"v1/deleteUser",
  GET_ENTITY_LOCALE:"v1/getEntityLocale",
  ORDER_DETAIL: "v1/orderDetails",
  GET_LOYALTY_CONTENT:"v1/getLoyaltyContent",
  EARN_CONTENT:"v1/getEarnContent",
  REDEEM_CONTENT:"v1/getRedeemContent",
  MEMBERSHIPS:"v1/memberships",
  BUY_SUBSCRIPTION:"v1/buySubscription",
  UPGRADE_SUBSCRIPTION:"v1/upgradeSubscription",
  CANCEL_SUBSCRIPTION:"v1/cancelSubscription",
  SUBSCRIBED_MEMBERSHIP:"v1/subscribedMembership",
  VALIDATE_PROMO_CODE:"v1/validatePromoCode",
  POINTS_DATA:"v1/getPointsData",
  POINTS_HISTORY:"v1/pointsHistory",
  GET_ABOUTUS_CONTENT:"v1/getAboutusContent",
  GET_HELPPOLICY__CONTENT:"/v1/getHelpPolicyContent",
  GET_PRIVACYNOTES__CONTENT:"v1/getPrivacyNotesContent",
  GET_TERMCONDITION__CONTENT :"v1/getTermConditionContent",
  GET_NOTIFICATION_SETTING:"v1/notificationSettings",
  UPDATE_NOTIFICATION_SETTING:"v1/updateNotificationSettings",
  GTECUISINES_And_CATEGORY:"v1/getCuisinesAndCategory"
  
}