export const images = {
    closeBold: require("../assets/png/icons/close-bold.png"),
    logo: require("./png/logo.png"),
    phone: require("./png/phone.png"),
    lock: require("./png/lock.png"),
    tick: require("./png/tick.png"),
    close: require("../assets/png/icons/close.png"),
    apple: require("./png/apple.png"),
    faceboook: require("./png/facebook.png"),
    google: require("./png/google.png"),
    unlock: require("./png/unlock.png"),

    bronze_reward: require("./png/icons/bronze-reward.png"),
    gold_reward: require("./png/icons/gold-reward.png"),
    platinum_reward: require("./png/icons/platinum-reward.png"),
    silver_reward: require("./png/icons/silver-reward.png"),
    tag: require("./png/icons/tag.png"),
    filter: require("./png/icons/filter.png"),

    cart: require("./png/cart.png"),
    cartFilled: require("./png/cartFilled.png"),
    user: require("./png/user.png"),
    medal: require("./png/medal.png"),
    destination: require("../assets/png/icons/destination.png"),
    location: require("./png/location.png"),
    remove: require("./png/remove.png"),
    up: require("./png/up.png"),
    visa: require("./png/icons/visa.png"),
    master: require("./png/icons/master.png"),
    dropdowndark:require("./png/icons/dropdown-dark.png"),
    canadaflag:require("./png/icons/canada-flag.png"),


    
    bin: require("./png/bin.png"),
    unfilledPhone: require("./png/unfilledPhone.png"),
    coffeecup: require("./png/coffee-cup.png"),


    burger1: require("./png/burger1.jpg"),
    burger2: require("./png/burger2.jpg"),
    burger3: require("./png/burger3.jpg"),
    burger4: require("./png/burger4.jpg"),
    home: require("./png/home.png"),
    homeFilled: require("./png/homeFilled.png"),
    plan: require("./png/plan.png"),
    planFilled: require("./png/planFilled.png"),
    qr: require("./png/qr.png"),
    rewards: require("./png/rewards.png"),
    notification: require("./png/notification.png"),
    profile: require("./png/profile.png"),
    search: require("./png/search.png"),
    settings: require("./png/settings.png"),
    star: require("./png/star.png"),
    starRounded: require("./png/starRounded.png"),
    mask: require("./png/Mask.png"),
    clock: require("./png/clock.png"),
    delivery: require("./png/delivery.png"),
    heart: require("./png/heart.png"),
    donate: require("./png/donate.png"),
    order: require("./png/order.png"),
    mapMarker: require("./png/mapMarker.png"),
    deliver: require("./png/deliver.png"),
    cardIcon: require("./png/cardIcon.png"),
    personQr: require("./png/personQr.png"),
    marker: require("./png/qrCorner/4.png"),
    marker2: require("./png/qrCorner/3.png"),
    marker3: require("./png/qrCorner/1.png"),
    marker4: require("./png/qrCorner/2.png"),
    minus: require("./png/minus.png"),
    plus: require("./png/plus.png"),
    delete: require("./png/delete.png"),
    checked: require("./png/checked.png"),
    burger: require("./png/burger.png"),
    earn: require("./png/earn.png"),
    redeem: require("./png/redeem.png"),
    addlocation: require("./png/add-location.png"),

    targetlocation: require("./png/target-location.png"),

    copy: require("./png/copy.png"),
    icecream: require("./png/icecream.png"),
    emptyCart: require("./png/emptyCart.png"),
    rewardFilled: require("./png/rewardFilled.png"),
    bgCard: require("./png/bgCard.png"),
    backArrow: require("./png/backArrow.png"),
    checkCircle: require("./png/checkCircle.png"),
    crossCircle: require("./png/crossCircle.png"),
    shippingFast: require("./png/shippingFast.png"),
    onBoarding1: require("./png/onBoarding1.png"),
    onBoarding2: require("./png/onBoarding2.png"),
    onBoarding3: require("./png/onBoarding3.png"),
    homeBanner1: require("./png/homeBanner1.png"),
    homeBanner2: require("./png/homeBanner2.png"),
    blankUuser: require("./png/blank-user.png"),

    arrow: require("./png/arrow.png"),
    edit: require("./png/edit.png"),
    cod: require("./png/cod.png"),
    applePay: require("./png/applePay.png"),
    card: require("./png/card.png"),
    order1: require("./png/order1.png"),
    arrowDown: require("./png/arrowDown.png"),
    reward1: require("./png/reward1.png"),
    reward2: require("./png/reward2.png"),
    reward3: require("./png/reward3.png"),
    reward4: require("./png/reward4.png"),
    reward5: require("./png/reward5.png"),
    reward6: require("./png/reward6.png"),
    confirmedOrder: require("./png/confirmedOrder.png"),
    map: require("./png/map.png"),
    rating: require("./png/rating.png"),
    homePin: require("./png/homePin.png"),
    chat: require("./png/chat.png"),
    filledPhone: require("./png/filledPhone.png"),
    pinIcon: require("./png/pinIcon.png"),
    heart1: require("./png/heart1.png"),
    heartFilled: require("./png/heartFilled.png"),
    info: require("./png/info.png"),
    orderDetail: require("./png/OrderDetail.png"),
    pointer: require("./png/Pointer.png"),
    plusBlue: require("./png/plusBlue.png"),
    qrFrame: require("./png/qrFrame.png"),
    loyaltypoints: require("./png/loyalty-points.png"),

}
